spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moco_xta_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ZZR/+w+emz8x5q5oRgRGI3LB2iymPETEXI+h/Xmv5r1FISNyei1gatmy1E/ubstE3LkPH+oDadK0w+Flrgi0la61fBH/jyKkR5MimolulFY96k5f6gkCnlYmXB9gkBSKI80BkIj8i2C6pf2oFFrO/iY/Z0AG6UivNrkcDNw6fVjWwjnkUzLUxuyOvKyUgU5sNsLp4wYmShKrO1SLpQx2CZI3WDwvmHJjgKIsQuAooTUnDlr4+B3/qvhoCTRhyF8uNB9+O5bfP4E+3NKY/YVrtq24nt/4dJWarmXTS9nw9znnAKvk6zmMk1YiFqrrxqUCyKIXAVazVadEYImbGWFqKcBEAFPqcktDuTI6axrJwxo=
      expiration: 86400000
      refresh-token:
        expiration: 604800000